steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/tp2/tp2-app:0.1', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/tp2/tp2-app:0.1']

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/tp2/tp2-app'
